# VARIABLES
SHELL=/bin/bash

#RULES 

solfeggietto:
	conda run -n mus2vid test_mp3/bach_solfeggietto.mp3 image.png

danube:
	conda run -n mus2vid test_mp3/blue_danube.mp3 image.png

gymnopedie:
	conda run -n mus2vid test_mp3/gymnopedie.mp3 image.png

hall:
	conda run -n mus2vid test_mp3/hall_of_the_mountain_king.mp3 image.png

sonata:
	conda run -n mus2vid test_mp3/moonlight_sonata.mp3 image.png

winter:
	conda run -n mus2vid test_mp3/vivaldi_winter.mp3 image.png

# .PHONY TARGET
.PHONY: solfeggietto danube gymnopedie hall sonata winter